set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports rst]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports finish]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD LVCMOS33} [get_ports stall]
set_property -dict {PACKAGE_PIN J3 IOSTANDARD LVCMOS33} [get_ports jump]

set_property -dict {PACKAGE_PIN B4 IOSTANDARD LVCMOS33} [get_ports sseg[6]]
set_property -dict {PACKAGE_PIN A4 IOSTANDARD LVCMOS33} [get_ports sseg[5]]
set_property -dict {PACKAGE_PIN A3 IOSTANDARD LVCMOS33} [get_ports sseg[4]]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD LVCMOS33} [get_ports sseg[3]]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD LVCMOS33} [get_ports sseg[2]]
set_property -dict {PACKAGE_PIN B3 IOSTANDARD LVCMOS33} [get_ports sseg[1]]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports sseg[0]]

set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS33} [get_ports an[3]]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD LVCMOS33} [get_ports an[2]]
set_property -dict {PACKAGE_PIN C1 IOSTANDARD LVCMOS33} [get_ports an[1]]
set_property -dict {PACKAGE_PIN H1 IOSTANDARD LVCMOS33} [get_ports an[0]]